### ISSUE TITLE
 Accepting unknown SSH host keys when using Paramiko 

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/odinControl#19]
It seems like the function, 

`node_ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())` is a security vulnerability as it can be used for man in the middle attack. Paramiko provides a way to load custom host file. For reference : https://stackoverflow.com/questions/39523216/paramiko-add-host-key-to-known-hosts-permanently.

This has to be fixed to prevent security vulnerability lingering with the code.

**Comment by schaffung** [comment]
Not an issue anymore with passwordless ssh criteria in force.
