### ISSUE TITLE
execute_command xmltodict error

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/odinControl#22]
[root@servera odinControl]# python3 rexe.py -l ./test.log -ll D -c ./Utilities/conf.yaml -e ./Utilities/execfile.yaml
Traceback (most recent call last):
  File "/home/Podant/odinControl/rexe.py", line 204, in <module>
    remote_executor.execute_command_file()
  File "/home/Podant/odinControl/rexe.py", line 166, in execute_command_file
    self.execute_command(command_node, command)
  File "/home/Podant/odinControl/rexe.py", line 115, in execute_command
    ret_dict['msg'] = xmltodict.parse(stdout_xml_string)['cliOutput']
  File "/usr/local/lib/python3.9/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

execfile.yaml:
10.70.43.228: 
  - "cat /home/test.py"
  - "gluster peer status"

10.70.43.101:
  - "cat /home/Podant/test.txt"

**Comment by aujjwal-redhat** [comment]
A condition that checks if `--xml` is not a part of the command should be provided to prevent the error to arise.

**Comment by srijan-sivakumar** [comment]
The --xml should be appended by the caller as all gluster cli commands have the provision to return an xml output as response. A check at the remote execution side would just add to the time taken to execute the command. This would rather be handled properly by keeping a global string of the form `gluster --xml` which can be used in the ops libraries.
